# Generated by Django 4.1.1 on 2023-04-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_fare_station_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kochi_fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=30)),
                ('Aluva', models.CharField(max_length=5)),
                ('Pulinchodu', models.CharField(max_length=5)),
                ('Companypady', models.CharField(max_length=5)),
                ('Ambattukavu', models.CharField(max_length=5)),
                ('Muttom', models.CharField(max_length=5)),
                ('Kalamassery', models.CharField(max_length=5)),
                ('Cochin_University', models.CharField(max_length=5)),
                ('Pathadipalam', models.CharField(max_length=5)),
                ('Edapally', models.CharField(max_length=5)),
                ('Changampuzha', models.CharField(max_length=5)),
                ('Palarivattom', models.CharField(max_length=5)),
                ('JLN_Stadium', models.CharField(max_length=5)),
                ('Kaloor', models.CharField(max_length=5)),
                ('Lissie', models.CharField(max_length=5)),
                ('MG_Road', models.CharField(max_length=5)),
                ('Maharajas', models.CharField(max_length=5)),
                ('Ernakulam_South', models.CharField(max_length=5)),
                ('Kadavanthra', models.CharField(max_length=5)),
                ('Elamkulam', models.CharField(max_length=5)),
                ('Vytilla', models.CharField(max_length=5)),
                ('Thaikoodam', models.CharField(max_length=5)),
                ('Petta', models.CharField(max_length=5)),
                ('Vadakkekotta', models.CharField(max_length=5)),
                ('SN_Junction', models.CharField(max_length=5)),
            ],
        ),
    ]
