name: Automate PythonAnywhere Bash Shell

on:
  push:
    branches:
      - master

jobs:
  run_pythonanywhere:
    runs-on: ubuntu-latest

    steps:
      - name: Send Bash Command to PythonAnywhere
        run: |
          curl -s -X POST \
          "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/consoles/" \
          -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
          -H "Content-Type: application/json" 
          
