name: Automate PythonAnywhere Bash Shell

on:
  push:
    branches:
      - master

jobs:
  run_pythonanywhere:
    runs-on: ubuntu-latest

    steps:
      - name: Send Bash Command to PythonAnywhere
        run: |
          curl -X POST -u "${{ secrets.PA_USERNAME }}:${{ secrets.PA_API_TOKEN }}" \
          "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/consoles/38366532/send_input/" \
          -H "Content-Type: application/json" \
          --data '{"input": "ls -la\n"}'
